baseURL = "https://yuzuafro.github.io/hugosample/"
languageCode = "ja-jp"
title = "Hugo Sample"
copyright = "&copy; Hugo Sample"
theme = "vienna"
hasCJKLanguage = true
paginate = 5

[params]
  twitter = "yuzu_afro"
  github = "yuzuafro"
  instagram = "yuzukonango"
  disqus = "yuzuafro"
  subtitle = "hugo sample blog"
